apis:
  - base: 139.24.161.180:9001
    searchModelSchemaByName: connector/searchModelSchemaByName
    searchData: connector/searchData
  - base: 192.168.66.136:9002
    graphqlController: graphqlController
    get_graphql_schema: graphqlController/schema
    jinzu_projectList: entities/projectList
    jinzu_projects: entities/projects
    jinzu_alarms: entities/alarms