apis:
  connector:
    base: data-layer-connector:80
    searchData: connector/searchData
    searchModelSchemaByName: connector/searchModelSchemaByName
  eagle:
    base: http://140.231.89.85:31294/
    entity: /api/entities
    entityLibraries: /api/entityLibraries
    entityLibrary-domain: /api/entityLibrary/domains
    graph: api/graphs
    relations: /api/relations
  entine:
    base: data-layer-api-engine:80
    entities: entities
oracle:
  db: xe
  password: IEC4SNC
  port: 1521
  server: 192.168.100.5
  username: IEC4SNC
