stages:
  - test
  - deploy


variables:
  namespace: release

before_script:
  - echo "Deploy to test automation"

test:
  stage: test
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - echo 'in test'

deploy:
  stage: deploy
  script:
    - echo 'in deploy'
    # 通过Dockerfile生成镜像
    - echo "${DOCKER_REPO_PREFIX} ${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
    - docker build -t ${DOCKER_REPO_PREFIX}${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} .
    - docker push ${DOCKER_REPO_PREFIX}${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
    - kubectl delete -f k8s.yaml -n ${namespace}
    - kubectl apply -f k8s.yaml -n ${namespace}
    - kubectl wait --for=condition=complete --timeout=3600s job/automation -n ${namespace}
    - curl -I -u admin:11b029ee01dd7e93525177cc20d66d6474  -X GET http://140.231.89.85:32693/job/data-layer-release/build?token=data-layer
  only:
    - dev