spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
#  server:
#    port: 8088
  endpoints:
    web:
      exposure:
        include: 'prometheus'
      base-path: /metrics

logging:
  level:
    com.siemens.devops.monitoring: debug #日志级别
  file:
    name: performance_monitoring.log #文件名 默认位置在当前项目根目录下
  logback:
    rollingpolicy:
      max-file-size: 5MB  #文件大小 超过会创建新文件
      file-name-pattern: performance_monitoring.%d{yyyy-MM-dd}.%i.log #文件名格式


#是否开启 swagger-ui
swagger:
  enabled: true

httpConfig:
  connectTimeout: 10000
  readTimeout: 10000

httpRequests:
- url: http://140.231.89.106:32760/graphql
  name: '[api-engine] search events by device name'
  type: POST
  headers:
    Content-Type: application/json
  body: '{Event(cond:"{device: {_eq: \"DC1\"}}") {eventTag device processNum coilNum timestamp}}'
  expectedCode: 100000

- url: http://140.231.89.106:32760/graphql
  name: '[api-engine] search steel size under processing'
  type: POST
  headers:
    Content-Type: application/json
  body: '{ Process_Steel_Size { steelTypeId steelSize id createTime updateUser createUser updateTime }}'
  expectedCode: 100000

- url: http://140.231.89.106:32760/graphql
  name: '[api-engine] search all alarm rules'
  type: POST
  headers:
    Content-Type: application/json
  body: '{ Process_Alarm_Rule { alarmType alarmRuleLowerValue alarmRuleValue alarmRuleUpperValue alarmRule id }}'
  expectedCode: 100000

- url: http://140.231.89.106:31751/api/connectors/searchData?fields=id,layerId,steelType&name=Process_Steel_Type
  name: '[connector] search steel types under processing'
  type: GET
  expectedCode: 0

- url: http://140.231.89.106:30397/api/v2/graphs/entities/81961000
  name: '[entity-mgmt] search entity by id'
  type: GET
  headers:
    Content-Type: application/json
  expectedCode: 100000

- url: http://140.231.89.106:30747/mapper/domain/Alarm_Data
  name: '[connector-configure] search mapper by entity name'
  type: GET
  headers:
    Content-Type: application/json
  expectedCode: 0
  # monitorPerformance: false
  # monitorFunction: false

# - url: http://140.231.89.106:32760/graphql
#   name: '[api-engine] search settings by coilNum equals P011C00800 and processNum equals R'
#   type: POST
#   headers:
#     Content-Type: application/json
#   body: '{ Setting(cond:"{_and:[{coilNum:{_eq:\"P011C00800\"}},{processNum:{_eq:\"R\"}}]}", authInfo:"", order:"value ASC") { id processNum coilNum value timestamp sensorId } }'
#   expectedCode: 100000
