rabbitmq:
  host: 140.231.89.85
  port: 30952
  virturalHost: /
  username: guest
  password: guest
  exchange: datalayer.exchange.out
  exchangeType: topic
  exchangeDurable: true
  queueDurable: true
  autoAck: true